import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProjectProvider } from "@/contexts/project-context";
import { ReactNode } from "react";
import cns from "classnames";
import { SidebarProvider } from "@/contexts/sidebar-context";
import { Sidebar } from "@/components/sidebar/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cns(geistSans.variable, geistMono.variable, "antialiased")}
      >
        <SidebarProvider>
          <ProjectProvider>
            <div className="h-screen w-screen flex flex-row">
              <Sidebar />
              {children}
            </div>
          </ProjectProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
